### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by sunbeomso** [RUB-SysSec/EthBMC#1]
Hi, I have three questions on using EthBMC.

**[Q1]** After following the build instruction, I tried to use EthBMC by running the command in README.md:
```
./target/release/ethbmc examples/rubixi/rubixi.yml
```
However, I encountered a following error message:
```
thread 'main' panicked at 'Could not initialize logger: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })', esvm/src/main.rs:60:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Could you explain how I can handle this error?
I am working on Ubuntu 18.04 and my rust version is 1.47.0-nightly.

**[Q2]**  I wonder how I can construct corresponding yml files to test new smart contracts  (other than contracts in ``examples`` directory).

Could you provide more guidance? For example, what things should be included in ``storage`` part?

**[Q3]** Is it possible to simply provide a source code (i.e., ``sol`` file) to use EthBMC? I wonder why I should create a yml file separately.

**Comment by Joool** [comment]
> **[Q1]** After following the build instruction, I tried to use EthBMC by running the command in README.md:
I have added a bugfix.


> **[Q2]** I wonder how I can construct corresponding yml files to test new smart contracts (other than contracts in `examples` directory).

I have added some instructions to the README, hope those help?

> **[Q3]** Is it possible to simply provide a source code (i.e., `sol` file) to use EthBMC? I wonder why I should create a yml file separately.

One of the main goals of the project was to simulate multi-environment accounts. Thus, the environment must be known initialized before analysis and hence the yaml file to set it up. A mode for analysing a `sol` file would be interesting but it is not implemented. We are open for contributions though.

**Comment by sunbeomso** [comment]
@Joool  Thanks for the answer.

>[Q1] After following the build instruction, I tried to use EthBMC by running the command in README.md:
>> I have added a bugfix.

=> After git pull and re-build (``cargo build --release``), the command ``./target/release/ethbmc examples/rubixi/rubixi.yml`` still produces an error message:
```
[2020-08-04][23:07:33][esvm][INFO] =========================================================
[2020-08-04][23:07:33][esvm][INFO] Starting first round.
[2020-08-04][23:07:33][esvm][INFO] =========================================================
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', esvm/src/se/expr/yice.rs:69:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
==========================================================================================

>[Q2] I wonder how I can construct corresponding yml files to test new smart contracts (other than contracts in examples directory).
>> I have added some instructions to the README, hope those help?

=> Thanks for updating the instructions!

==========================================================================================
>[Q3] Is it possible to simply provide a source code (i.e., sol file) to use EthBMC? I wonder why I should create a yml file separately.
>> One of the main goals of the project was to simulate multi-environment accounts. Thus, the environment must be known initialized before analysis and hence the yaml file to set it up. A mode for analysing a sol file would be interesting but it is not implemented. We are open for contributions though.

=> Could you explain what you meant by ``"to simulate multi-environment accounts"`` in more detail?

**Comment by Joool** [comment]
> => After git pull and re-build (`cargo build --release`), the command `./target/release/ethbmc examples/rubixi/rubixi.yml` still produces an error message:

You seem to be missing an installation of yice (see Requirements), if you want to use EthBMC with a different solver use `--solver` flag.

> => Could you explain what you meant by `"to simulate multi-environment accounts"` in more detail?

Analyzing the behaviour of two accounts in conjunction (i.e., parity), see the paper for details.

**Comment by sunbeomso** [comment]
Thank you for the answer!
